// src/core/EditorAPI.ts (Assumed location of interface definition)
// ...
export interface EditorAPI {
    // ... existing methods ...
    showToast: (type: ToastType, message: string) => string | number | void;
    // ... other methods ...
}