// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://bwgdgbgwkgiwkwabynvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3Z2RnYmd3a2dpd2t3YWJ5bnZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDAzNjYsImV4cCI6MjA3NTQ3NjM2Nn0.3KnONvezPm3TbohZnunggpUPZhO-ktCp9M9QvBM6POU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);